manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: joaopedropio
      url-base: https://github.com/joaopedropio
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: v0.2
      # revision: main
      import: app/west.yml
    - name: snake-module
      remote: joaopedropio
      revision: master
      # revision: zephyr-4.1
  self:
    path: config
